apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
