apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ .Values.repoPrefix }}{{ .Values.frontend.deployment.image }}:{{ required "You must specify the version to be deployed" .Values.frontendDeploymentTag }}
        imagePullPolicy: {{ .Values.frontend.deployment.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
