kind: pipeline
name: default

steps:
    - name: install
      image: node
      commands:
          - cd frontend
          - npm ci

    - name: lint
      image: node
      depends_on: [install]
      commands:
          - cd frontend
          - npm run lint

    - name: test
      image: node
      depends_on: [install]
      commands:
          - cd frontend
          - npm run test

    - name: build-and-typescript-check
      image: node
      depends_on: [install]
      commands:
        - cd frontend
        - npm run build

trigger:
    event:
        - pull_request
