# Default values for auction-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  secretName: "sidestream-github"

awsChamberAccountSecretName: "sidestream-tech-chamber-read-secret"
repoPrefix: "ghcr.io/sidestream-tech/auction-ui/"

frontend:
  name: "frontend"
  containerPort: 80
  deployment:
    image: "frontend"
    pullPolicy: "IfNotPresent"

botTwitter:
  name: "bot-twitter"
  deployment:
    image: "bot-twitter"
    pullPolicy: "IfNotPresent"
  # AWS SSM path for chamber to read secrets for the pods from, e.g., `auction-ui/staging/bot`
  secretChamberPath:

ingress:
  class: nginx
  isCertManagerActivated: true
  isTlsActivated: true
  tlsSecretName: "auction-ui-tls-certificate"
